version: '3'

services:

    postgres_db:
        image: postgres:12.0-alpine
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        ports:
            - "${HOST_PORT}:5432"
        volumes:
            - postgres:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASS=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}

volumes:
    postgres:
